### ISSUE TITLE
`mock_clinical_timelines_app()` is not exported

### ISSUE THREAD

**Issue by donyunardi** [Boehringer-Ingelheim/dv.clinlines#10]
I was trying to follow your README to run the clinical timeline module:
https://github.com/Boehringer-Ingelheim/dv.clinlines/blob/6cda4601fda656c9006728374a68e0b2bca9a414/README.md?plain=1#L41

And run into this error:

```
> dv.clinlines::mock_clinical_timelines_app()
Error: 'mock_clinical_timelines_app' is not an exported object from 'namespace:dv.clinlines'
```

I checked the NAMESPACE and I don't see `mock_clinical_timelines_app` is exported.

Two things can happen, either update the README to three colon to access this internal function:
`dv.clinlines:::mock_clinical_timelines_app()`

Or `@export` the function.

I'm more than happy to push a PR if you tell me how you would like to proceed.

**Comment by iglauss** [comment]
Thank you so much for pointing that out! I have exported the mock app within the 1.1.0 release. Appreciate your help in improving the package!
